name: 'Generate Docker Images'

on:
    push:
        branches:
            - master

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v2.3.5
        -   name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v1
        -   name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v2
            with:
                version: latest
        -   name: Build base-image
            run: |
                docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 -t itachi1706/rpi-ftb:jdk8-base --pull --push -f baseimage.txt .

    release:
        runs-on: ubuntu-latest
        needs: setup
        steps:
        -   name: Checkout
            uses: actions/checkout@v2.3.5
        -   name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v1
        -   name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v2
            with:
                version: latest
        -   name: Run Script
            run: |
                chmod +x build.sh
                ./build.sh
